name: oneroot
description: Introducing our innovative root & jailbreak detection plugin called OneRoot, a powerful tool that allows you to check the part of your device security.
version: 0.0.7
homepage: https://github.com/udithperera-dev/oneroot

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.akurupela.oneroot
        pluginClass: OnerootPlugin
      ios:
        pluginClass: OnerootPlugin

topics:
  - oneroot
  - android
  - ios
  - root-detection
  - jailbreak-detection